### ISSUE TITLE
way to configure more than a single site?

### ISSUE THREAD

**Issue by columbian-chris** [damianlewis/vagrant-web-vm#4]
Is there a way I can provision more than a single dev site in my install?  Maybe change the config to where the "site" variable is an array then make the virtual host config into a loop to create a new site for each site defined in the "site" array?

**Comment by damianlewis** [comment]
No, multiple sites can't be created from the config file. Of course, you can create your own nginx/apache virtual hosts.

It might be something I'll look into for future releases.
