### ISSUE TITLE
What is the SSH password?

### ISSUE THREAD

**Issue by svivian** [damianlewis/vagrant-web-vm#5]
I just updated my box `damianlewis/lemp-php7.1` to v1.1.0 but when I run `vagrant ssh` it's now asking for a password (it didn't before). What is the password?

**Comment by svivian** [comment]
OK that may have been because the box was not properly halted. However, I halted the box and ran `vagrant up` again, now it's not loading at all:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

Any ideas?

**Comment by svivian** [comment]
I found an issue on hashicorp about this "authentication failure" error, in particular [this comment](https://github.com/hashicorp/vagrant/issues/5186#issuecomment-312349002). Firstly to answer my original question, the password is **vagrant**.

The bit under "Got Ubuntu box working" about deleting `vagrant_private_key ` is what solved it for me. I don't know enough about Vagrant to know if it a problem with your box or with Vagrant itself, but from the context it sounds like there is something misconfigured in the box.

**Comment by damianlewis** [comment]
Yes, the boxes use the default password for Vagrant which is `vagrant`.

The issue with ssh, is that the randomly generated key is included with the boxes. This causes a conflict if you upgrade the box whilst you still have VM's using a previous version. As suggested, you could remove the private key or re-create the VM, i.e. `vagrant destroy` then `vagrant up`.

I've released a new version of the boxes, without the ssh key, so hopefully this will have fixed the issue on new VM's using these boxes.
